### ISSUE TITLE
Limiting AMP to one Page type

### ISSUE THREAD

**Issue by martinviolet88** [SilverStripers/amp#1]
HI, thanks for the module, I have a project where just want AMP to work on one Page type, and not on all pages. Is this possible?
Love to hear from you, 

Thanks!

**Comment by fonsekaean** [comment]
Hello @martinviolet88 

With the way it is set up you cant do that right now. However with a few modifications to the module you'd be able to do restrict to only a few page types. I think this a a good feature to have too. You are welcome to send us a pull request. 

Cheers

**Comment by fonsekaean** [comment]
Hello @martinviolet88 

This functionality has been added on to the module now. 

Closing this issue.
