### ISSUE TITLE
Conflict with facebook/php-business-sdk v.10.0

### ISSUE THREAD

**Issue by gacelabs** [SilverStripers/amp#2]
installing fb sdk shows:
Problem 1
    - silverstripers/amp dev-master requires guzzlehttp/guzzle 6.3.1 -> satisfiable by guzzlehttp/guzzle[6.3.1] but these conflict with your requirements or minimum-stability.
    - silverstripers/amp dev-master requires guzzlehttp/guzzle 6.3.1 -> satisfiable by guzzlehttp/guzzle[6.3.1] but these conflict with your requirements or minimum-stability.
    - silverstripers/amp dev-master requires guzzlehttp/guzzle 6.3.1 -> satisfiable by guzzlehttp/guzzle[6.3.1] but these conflict with your requirements or minimum-stability.
    - Installation request for silverstripers/amp dev-master -> satisfiable by silverstripers/amp[dev-master].

**Comment by matthinck** [comment]
Hi @gacelabs 

I also have this issue, where the the facebook/php-business-sdk 10.0 needs guzzlehttp/guzzle 6.5.x
however silverstripers/amp only needs guzzlehttp/guzzle 6.3.1

@fonsekaean 
What is needed to update the dependancy from Guzzle 6.3 to Guzzle 6.5 ?
